# Generated by Django 5.2 on 2025-04-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='user',
        ),
    ]
