# Generated by Django 5.2 on 2025-05-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiles",
            name="phone_number",
            field=models.CharField(max_length=70),
        ),
    ]
