# Generated by Django 5.2 on 2025-05-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profiles_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profiles",
            name="phone_number",
        ),
    ]
