# Generated by Django 5.2 on 2025-05-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_remove_profiles_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiles",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
